apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: random-num-servicemonitor
  namespace: monitoring
  labels:
    release: kind-prometheus
spec:
  selector:
    matchLabels:
      app: random-num
  endpoints:
    - port: metrics
      interval: 10s
  namespaceSelector:
    matchNames:
    - default